services:
  db:
    image: mysql/mysql-server:5.7
    hostname: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vats
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local